spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org.apache.catalina.core.ContainerBase: off

